### ISSUE TITLE
bilara config data—make it flat!

### ISSUE THREAD

**Issue by sujato** [suttacentral/bilara-data#596]
**UPDATE LATEST CHANGES**

https://github.com/suttacentral/bilara-data/blob/unpublished/_publication-v2.json
https://github.com/suttacentral/bilara-data/blob/unpublished/_project-v2.json

## summary

Two of our config files are fairly complex, and it would be useful to be able to view them as a spreadsheet. To this end, make them flat so they can be easily converted to and from `tsv` etc.

Note that not all files need to be made flat. Most files are pretty simple, so viewing them as JSON is fine.

## roadmap

- [X]  introduce `publication-v2` and `project-v2`
- [x] build the "publications" pipeline on v2
     - meanwhile, maintain both old and new files (sorry @carmi!)
- [ ] when "publications" is complete, transition other apps to v2
- [ ] when complete, remove old version.

### structure

- Overall structure is a flat array of objects.
- Value may be an array of values. This is used for multiple authors, also for editions.

### edition

To avoid duplicating data, the `editions` data has been removed completely from `publication.json`. There is only the bare minimum to point to the editions: namely, URL for the editions folder. This doesn't exist yet!

- add field for "first_published"

### license

License fields are all flattened.

Use Public Domain for all root texts, not CC0. CCO is used when the copyright is owned and the owner wishes to relinquish it. There is no copyright on root texts, thus no need or legal justification for releasing it.

### rename fields to suit root texts and translations

- translation_process ---> creation_process
- translation_description   ---> text_description
- author_  ---> creator_

Note that for root texts, the `text_uid` is not the division (which is the case for translations) but the UID for the edition itself, eg. `dpcv`, `sct`, `ms`. Look inside `root/LANGUAGE` and you'll find it!

### collaboration

The concept of collaborator has been removed.

https://github.com/suttacentral/bilara-data/issues/597

 Instead, if there are multiple authors, an array is used. Eg.

```
    "author_uid": [
      "gnlaera",
      "vitor"
    ],
    "author_name": [
      "Gabriel Laera",
      "Vitor Guimarães"
    ],
    "author_github_handle": [
      "gnlaera",
      "vngmar"
    ],
```

 **notes**

https://github.com/suttacentral/bilara-data/commits/unpublished?author=ViceroyFaust

scpub13: appears inactive. Unpublished translations up to mid-2020

scpub26: user ashinsarana appears inactive. I have made nyeinchanaye the only user. There are a few suttas that were included under shin sarana's name. We should clarify.

>Also note that for the suttaplex, where the `creator_name` is used in translations, use `root title`. (This is just a note so I don't forget, we'll do this on the front end when the time comes.)

**Comment by firepick1** [comment]
There is always a conflict between hierarchical and tabular data representation. Neither one is right for all use cases.  Tables suck at editing relationships, hierarchies suck at editing entries. Relational databases were introduced to solve the problems of hierarchical data. And yet now we've gone full circle back to embracing hierarchy in object databases. So in actuality, we really do need both forms of data and transformation is often a necessary burden.

Perhaps the first step might be for Carmi to document her spreadsheet to enumerate and define the purpose of each column. This document will help us develop a transformation or recode strategy. The spreadsheet should represent all current and foreseen human publication needs. In contrast, the JSON represents current computational needs. Since the computational needs are spread out across applications, it makes sense to start with the focal point of user change, which is Carmi's spreadsheet.

We can even store Carmi's spreadsheet in a TSV file in a new "sc-publication.tsv" file in bilara-data. And Carmi could document her process and data fields in the bilara-data wiki.  From this auspicious beginning, we can then determine the best path for each application to follow in order to honor the truth and light of Carmi's spreadsheet.

**Comment by ccronje** [comment]
Thanks @firepick1. I created the spreadsheet 12 months ago when I started. Haven't used it since but at the time it helped me to see the properties and corresponding values that were inconsistent/missing. I used the built-in JSON conversion in Excel at the highest hierarchical level, then copied it over to Google Sheets (which didn't have the same functionality). I recorded the properties in the wiki https://github.com/suttacentral/bilara-data/wiki/Publication-metadata.

In terms of strategy, I wonder if it's an opportunity to revisit standardising publication properties? The publications project https://github.com/orgs/suttacentral/projects/2/views/1 and this recent issue prompted me to think about it again https://github.com/suttacentral/suttacentral/issues/2356 i.e. **using schema.org properties and microdata to mark up the html**. It depends on the overall benefits, and if schema.org supports the structure of the EBTs (e.g. Collection, Book, Chapter - see table under https://schema.org/CreativeWork). A question maybe for Bhante @sujato and @blake-sc?

**Comment by firepick1** [comment]
Ahhhhh. So the spreadsheet is itself legacy in your workflow.  OK, then my recommendation changes to what you just suggested. Documenting existing convention is crucial. And we have to be very careful not to dismiss fields which may have obscure uses not remembered by any of us.

After documenting what is, we can then discuss standardization. My concern here is that premature or incomplete standardization inevitably creates huge messes that are worse than existing problems. Schema changes are as dangerous as neurosurgery. A single bad schema change can kill companies.  It will need to come down to a meticulous and laborious investigation for each proposed field change.  Name changes alone can be disastrous.  

To survive a standardization, best practice is to:

1) ADD new standardized fields
2) SLOWLY convert apps to use new standardized fields while maintaining BOTH unstandard and standard fields
3) DELETE old fields

As you can see, this is like defusing a cluster bomb minefield left after first world countries litter the world with bomblets. The caution required is immense.

**Comment by sujato** [comment]
The standards discussion is probably another thread, but FWIW I wonder if another approach might be possible. Given that in many cases the data we use will already have its equivalent in various standardized formats, maybe we could separate out the standards from the data?

- We keep doing what we're doing
- `bilara-standards` becomes, as it were, an app built on top of bilara-data
- relevant fields are extracted from bilara data and transformed into standards-compliant form
- use Github Actions for this
- data in this form form is published as distinct files, or integrated as metadata
- drink mead and frolic

This way we can keep building SC/Bilara/Voice and our only concern is to design our data in the best way for us. We don't have to keep looking over our shoulder every time to make sure we fit in with someone else's schema. Then someone who knows the schema can interpret our data the best way possible for the schema. Any issues or complications won't affect the apps, and any third party sources that want standardized data can grab them.

***

Back to the matter at hand!

Note that, since we are about to employ STXnext for a period, we can get them to do this change and do the relevant testing in Bilara, SC, and Voice. And whatever else.

**Comment by firepick1** [comment]
I've always wondered what mead tastes like. 

The key point I'd like to make is that ADD-itive changes are benign and can be enthusiastically pursued. The cost comes from altering existing field name or semantics. So, the simple solution is to create author2, publication2, etc. in whatever canonical form suits all known tasks. The suffering of schema change only manifests when existing schemas are mutated without regard for current app needs.  

This is "not killing" for data schemas. They die and pass away on their own.
